# Generated by Django 5.1.4 on 2024-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_failedloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
